---
tags: [hadoop,yarn,boot]
projects: [spring-hadoop]
---
:spring_version: 4.0.5.RELEASE
:spring_boot_version: 1.0.2.RELEASE
:spring_hadoop_version: 2.0.0.RC4
:java_version: 1.6
:Component: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Component.html
:SpringComponentScanAnnotation: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/context/annotation/ComponentScan.html
:SpringProfileAnnotation: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/context/annotation/Profile.html
:SpringConfigurationAnnotation: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/context/annotation/Configuration.html
:SpringBeanAnnotation: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/context/annotation/Bean.html
:SpringApplication: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html
:ConfigurationProperties: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/context/properties/ConfigurationProperties.html
:EnableAutoConfiguration: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/autoconfigure/EnableAutoConfiguration.html
:YarnClient: http://docs.spring.io/spring-hadoop/docs/{spring_hadoop_version}/api/org/springframework/yarn/client/YarnClient.html
:YarnAppmaster: http://docs.spring.io/spring-hadoop/docs/{spring_hadoop_version}/api/org/springframework/yarn/am/YarnAppmaster.html
:YarnContainer: http://docs.spring.io/spring-hadoop/docs/{spring_hadoop_version}/api/org/springframework/yarn/container/YarnContainer.html
:YarnComponentAnnotation: http://docs.spring.io/spring-hadoop/docs/{spring_hadoop_version}/api/org/springframework/yarn/annotation/YarnComponent.html
:OnContainerStartAnnotation: http://docs.spring.io/spring-hadoop/docs/{spring_hadoop_version}/api/org/springframework/yarn/annotation/OnContainerStart.html
:SpringYarnBootApplication: http://docs.spring.io/spring-hadoop/docs/{spring_hadoop_version}/api/org/springframework/yarn/boot/app/SpringYarnBootApplication.html
:DefaultYarnContainer: http://docs.spring.io/spring-hadoop/docs/{spring_hadoop_version}/api/org/springframework/yarn/container/DefaultYarnContainer.html
:FsShell: http://docs.spring.io/spring-hadoop/docs/{spring_hadoop_version}/api/org/springframework/data/hadoop/fs/FsShell.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-yarn-basic
:yarn_base_dist: gs-yarn-basic-single-app
This guide walks you through the process of creating a Spring Hadoop YARN application.

== What you'll build

You'll build a simple Hadoop YARN application with Spring Hadoop and
Spring Boot. In other examples you may have seen a multi-project
structure to be used but by all means this is not necessary and in
this sample only a single project and jar file is created.


== What you'll need

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]
 - Local single-node instance based on Hadoop 2.2.0 or later. The Apache Hadoop site has some http://hadoop.apache.org/docs/r2.2.0/hadoop-project-dist/hadoop-common/SingleCluster.html[instructions].

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[scratch]]
== Set up the project

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_system_intro.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_system_intro_yarn.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_directory_structure_yarn_single_hello.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_both_builds_multi.adoc[]

`build.gradle`
[source,java]
----
include::initial/build.gradle[]
----

`settings.gradle`
[source,java]
----
include::initial/settings.gradle[]
----

In the above gradle build file we simply create three different jars, each having classes for its specific role. These jars are then repackaged by Spring Boot's gradle plugin to create an executable jar.

[[initial]]
== Create an Application

Here you create `Application` and `HelloPojo` classes.

`gs-yarn-basic-single-app/src/main/java/hello/Application.java`
[source,java]
----
include::complete/gs-yarn-basic-single-app/src/main/java/hello/Application.java[]
----

In the above `Application`, notice how we added the
{SpringComponentScanAnnotation}[`@ComponentScan`] 
annotation at the main class level and the
{YarnComponentAnnotation}[`@YarnComponent`] annotation on the
inner `HelloPojo` class. 

`HelloPojo` class is a simple `POJO` in a sense that it doesn't extend any Spring YARN base classes. What we did in this class:

 - We added a class level {YarnComponentAnnotation}[`@YarnComponent`] annotation.
 - We added a method level {OnContainerStartAnnotation}[`@OnContainerStart`] annotation
 - We `@Autowired` a Hadoop's `Configuration` class
 - We added a method level {SpringProfileAnnotation}[`@Profile`] annotation

{YarnComponentAnnotation}[`@YarnComponent`] is a stereotype
annotation, providing a Spring {Component}[`@Component`] annotation.
This is automatically marking a class to be a candidate for having
{YarnComponentAnnotation}[`@YarnComponent`] functionality. We
specifically use {SpringProfileAnnotation}[`@Profile`] to mark bean to
be created only if `container` profile is active. Having a
{SpringComponentScanAnnotation}[`@ComponentScan`] present in
`Application` class will then instruct context to automatically create
beans by classpath scanning.

Within this class we can use
{OnContainerStartAnnotation}[`@OnContainerStart`] annotation to mark a
public method with `void` return type and no arguments act as an entry
point for some application code that needs to be executed on Hadoop.

To demonstrate that we actually have some real functionality in this
class, we simply use Spring Hadoop's {FsShell}[`@FsShell`] to list
entries from the root of the `HDFS` file system. We needed to have
Hadoop's `Configuration` which is prepared for you so that you can
just rely on autowiring for access to it.

The `main()` method uses Spring Boot's `SpringApplication.run()`
method to launch an application. What happens next depends on
configuration and detected condition on {YarnClient}[`YarnClient`],
{YarnAppmaster}[`YarnAppmaster`] or {YarnContainer}[`YarnContainer`].

== Create an Application Configuration

Create a new yaml configuration file for gs-yarn-basic-single-app project.

`gs-yarn-basic-single-app/src/main/resources/application.yml`
[source,yaml]
----
include::complete/gs-yarn-basic-single-app/src/main/resources/application.yml[]
----

NOTE: Pay attention to the `yaml` file format which expects correct indentation and no tab characters.

Final part for your application is its runtime configuration, which glues all the components together, which then can be executed as a Spring YARN application. This configuration act as source for Spring Boot's {ConfigurationProperties}[`@ConfigurationProperties`] and contains relevant configuration properties which cannot be auto-discovered or otherwise needs to have an option to be overwritten by an end user.

This way you can define your own defaults for your environment. Because these {ConfigurationProperties}[`@ConfigurationProperties`] are resolved at runtime by Spring Boot, you even have an easy option to overwrite these properties either by using command-line options, environment variables or by providing additional configuration property files.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_yarn_application_single.adoc[]

== Run the Application

Now that you've successfully compiled and packaged your application, it's time to do the fun part and execute it on Hadoop YARN.

To accomplish this, simply run your executable client jar from the projects root dirctory.

[source]
----
$ java -jar gs-yarn-basic-single-app/target/gs-yarn-basic-single-app-0.1.0.jar
----

To find Hadoop's application logs, you need to do a simple find within the hadoop clusters configured userlogs directory.

[source]
----
$ find hadoop/logs/userlogs/ | grep std
hadoop/logs/userlogs/application_1395578417086_0001/container_1395578417086_0001_01_000001/Appmaster.stdout
hadoop/logs/userlogs/application_1395578417086_0001/container_1395578417086_0001_01_000001/Appmaster.stderr
hadoop/logs/userlogs/application_1395578417086_0001/container_1395578417086_0001_01_000002/Container.stdout
hadoop/logs/userlogs/application_1395578417086_0001/container_1395578417086_0001_01_000002/Container.stderr
----

Grep logging output from a `HelloPojo` class.

[source]
----
$ grep HelloPojo hadoop/logs/userlogs/application_1395578417086_0001/container_1395578417086_0001_01_000002/Container.stdout
[2014-03-23 12:42:05.763] boot - 17064  INFO [main] --- HelloPojo: Hello from HelloPojo
[2014-03-23 12:42:05.763] boot - 17064  INFO [main] --- HelloPojo: About to list from hdfs root content
[2014-03-23 12:42:06.745] boot - 17064  INFO [main] --- HelloPojo: FileStatus{path=hdfs://localhost:8020/; isDirectory=true; modification_time=1395397562421; access_time=0; owner=root;
group=supergroup; permission=rwxr-xr-x; isSymlink=false}
[2014-03-23 12:42:06.746] boot - 17064  INFO [main] --- HelloPojo:
FileStatus{path=hdfs://localhost:8020/app; isDirectory=true;
modification_time=1395501405412; access_time=0; owner=hadoop; group=supergroup; permission=rwxr-xr-x; isSymlink=false}
----


== Summary

Congratulations! You've just developed a Spring YARN application! 

